export const SAMPLE_TICKETS = [
  "Hi, this is Dana Kowalczyk in Acme Widgets accounting. I changed my password yesterday like the reminder told me to and now I cannot get into anything. My laptop says the username or password is wrong and my phone keeps asking me for the password over and over. I have a month end close report due Thursday.",
  "The big printer on floor 2 outside the Acme Widgets sales bullpen is jammed again. There is paper stuck somewhere inside it and the front panel shows a wrench symbol. Four of us have been sending print jobs to it all morning and nothing comes out. We can walk to floor 3 to print but it is a hike.",
  "Marcus Trent here, remote from home. The VPN drops about every ten minutes. It reconnects on its own after a bit but anything I had open on the Acme Widgets file share dies and I lose whatever I was typing. Started sometime last week. My home wifi seems fine, Netflix works.",
  "my computer is being weird. it was fine friday. now it is slow and sometimes the screen goes black for a second and comes back. also there is a noise. i am not sure what else to tell you. Priya Raman, Acme Widgets warehouse office.",
  "Outlook on my desktop has not pulled in new mail since about 3pm yesterday. It just says Disconnected in the bottom corner. I can see all my new messages fine on my phone and on the web version, so I know mail is still coming in. Tom Bexley, Acme Widgets facilities.",
  "Hi, since this morning Outlook keeps popping up a window asking for my password. I type it in and it goes away for like 5 minutes and then comes right back. Email works fine on my phone and in the browser. I haven't changed my password recently that I know of. It's driving me crazy, can someone look at it when you get a chance? Thanks, Dana Whitfield Accounts Payable, ext 4412",
  "my second monitor wont turn on. no power light at all. tried plugging it into a different outlet under my desk and still nothing. the other monitor works so im not dead in the water, just slower. desk B-214 in engineering - Marcus",
  "I work remote 3 days a week and for the past week the VPN drops every 20-30 minutes. It reconnects on its own after a minute or two but it kills my Teams calls with customers and I lose whatever I had open in the ERP. My home internet is fine, Netflix and everything else works without issues. I think it started after the update that installed last Monday but I'm not 100% sure. Laptop tag AW-L-0387 Rachel Nguyen Inside Sales",
  "Hello IT, We have a new Quality Engineer starting Monday, September 28. Please set her up with the following: Name: Priya Raman Title: Quality Engineer Manager: Tom Becker Department: Quality She'll need a network login and email, access to the Quality shared drive, and read-only access to the ERP. Basically the same access Tom's other engineers have. Her laptop should already be ordered through Desktop. Thank you, Lauren Pike Human Resources",
  "I got an email about 20 minutes ago that looked like it was from payroll saying I needed to confirm my direct deposit info before Friday or I wouldn't get paid. I clicked the link and it took me to a login page that looked like ours so I put in my username and password. Then I got the MFA prompt on my phone and I approved it. After that the page just went blank. Now I'm seeing 2 emails in my Sent folder that I didn't send, they went to a bunch of people in my contacts. I haven't touched anything else. What do I do?? ---------- Forwarded message --------- From: Acme Payroll <payroll-update@acme-widgets-hr.net> Subject: Action Required: Verify Direct Deposit Information Your direct deposit information must be re-verified before the next pay cycle. Failure to verify within 24 hours will delay your payment. [Verify Now] Greg Solano Purchasing",
  "[Phone call logged by Service Desk, 7:42 AM] Caller: Denise Harper, Shipping Supervisor Caller reports the entire warehouse lost wifi about 10 minutes ago. All handheld scanners show \"no network.\" The office side of the building seems fine and desk phones work. Trucks are waiting at docks 3 through 7 and they can't scan or ship anything until it's back. Caller says she needs someone out there now. Nobody on the floor touched anything that she knows of, but maintenance was working in the ceiling near the east wall yesterday.",
  "My laptop did an update overnight and now when I turn it on it's a blue screen asking for a BitLocker recovery key. I don't have any key. I'm presenting to the board at 1:00 today and my entire deck is on this laptop (I think some of it is in OneDrive but not the latest version). Please call my cell, I'm in the building. Steve Callahan VP of Sales",
  "Jake Morrow's last day was Friday. He was let go, not a resignation. I just noticed he's showing as online in Teams this morning, which shouldn't be possible. Can someone make sure everything is shut off? He also had a login to the supplier portal and he knew the shared admin password for the CNC machine PCs on the shop floor. Please let me know when it's done. Brian Kessler Manufacturing Manager",
  "Hi, could I get Visio installed on my PC? I'm starting to map out our receiving process and Tom said he approved it. No rush, sometime this week or next is fine. Thanks! Alicia Grant Operations Analyst PC tag AW-D-1122",
  "label printer at shipping station 2 is printing blank labels. it feeds the label out but nothing is on it. we already put a new roll in and turned it off and on. now theres a red light blinking. we are sending everything to station 1 for now but its backing things up pretty bad this afternoon - Luis, shipping",
  "I found a USB flash drive on the ground in the employee parking lot this morning near the side entrance. It has a sticker on it that says \"Q3 Salaries.\" I did NOT plug it in anywhere. It's sitting on my desk right now. Who should I give it to? Maria Delgado Customer Service",
  "Hi IT, We have a customer visit next Thursday at 10 AM in Conference Room B. Four people will be in the room and two will join remotely on Teams. We'll need the projector working and someone to make sure the camera and speakerphone are set up before they arrive. Last time we used that room the audio cut out, so if someone could test it beforehand that would be great. Thanks, Karen Ortiz Executive Assistant",
];

export function pickSampleTicket(currentText) {
  const others = SAMPLE_TICKETS.filter((ticket) => ticket !== currentText);
  const pool = others.length > 0 ? others : SAMPLE_TICKETS;
  return pool[Math.floor(Math.random() * pool.length)];
}
